import "./globals.css";
import { generalSans, notoSans } from "./fonts";

export const metadata = {
  title: "Saumya Talwani",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en" className={`${generalSans.variable} ${notoSans.variable}`}>
      <body>
        {children}
      </body>
    </html>
  );
}
